[package]
name = "reddsa"
edition = "2018"
# When releasing to crates.io:
# - Update html_root_url
# - Update CHANGELOG.md
# - Create git tag.
version = "0.0.0"
authors = [
    "Henry de Valence <hdevalence@hdevalence.ca>",
    "Deirdre Connolly <durumcrustulum@gmail.com>",
    "Chelsea Komlo <me@chelseakomlo.com>",
    "Jack Grigg <jack@electriccoin.co>",
]
readme = "README.md"
license = "MIT OR Apache-2.0"
repository = "https://github.com/zcash/reddsa"
categories = ["cryptography"]
keywords = ["cryptography", "crypto", "zcash"]
description = "A standalone implementation of the RedDSA signature scheme."

[package.metadata.docs.rs]
features = ["nightly"]

[dependencies]
blake2b_simd = "0.5"
byteorder = "1.3"
digest = "0.9"
#ff = "0.9"
ff = { git = "https://github.com/nuttycom/ff", branch = "bitvec-0.22" }
#group = "0.9"
group = { git = "https://github.com/nuttycom/group", branch = "bitvec-0.22" }
#jubjub = "0.6"
jubjub = { git = "https://github.com/nuttycom/jubjub", branch = "bitvec-0.22" }
rand_core = "0.5"
serde = { version = "1", optional = true, features = ["derive"] }
thiserror = "1.0"
zeroize = { version = "1", default-features = false, features = ["zeroize_derive"] }

[dependencies.pasta_curves]
git = "https://github.com/nuttycom/pasta_curves.git"
branch = "bitvec-0.22"

[dev-dependencies]
bincode = "1"
criterion = "0.3"
lazy_static = "1.4"
proptest = "0.10"
rand = "0.7"
rand_chacha = "0.2"

[features]
nightly = []
default = ["serde"]

[[bench]]
name = "bench"
harness = false
